
executor: LocalExecutor
dags:
  persistence:
    enabled: false

webserver:
  extraVolumes:
    - name: dag-hostpath
      hostPath:
        path: /mnt/airflow-dags
  extraVolumeMounts:
    - name: dag-hostpath
      mountPath: /opt/airflow/dags
      readOnly: true

  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
scheduler:
  extraVolumes:
    - name: dag-hostpath
      hostPath:
        path: /mnt/airflow-dags
  extraVolumeMounts:
    - name: dag-hostpath
      mountPath: /opt/airflow/dags
      readOnly: true
